global:
  domain: "coralogix.us"
  clusterName: "aks-cicd-2568"
  defaultApplicationName: "aks-cicd-2568-defaultApplicationName"
  defaultSubsystemName: "aks-cicd-2568-defaultSubsystemName"
  logLevel: "info"

  extensions:
    kubernetesDashboard:
      enabled: true
