version: '3.3'
services:

  # OpenTelemetry Collector
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./confs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./confs/server.crt:/etc/tls/server.crt
      - ./confs/server.key:/etc/tls/server.key
      - ./confs/rootCA.crt:/etc/tls/rootCA.crt
    ports:
      - "4317:4317" # OTLP over gRPC receiver
      - "9464:9464" # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
    networks:
      - my_net

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    ports:
      - "14250:14250" # Collector gRPC
      - "16686:16686" # Web HTTP
    networks:
      - my_net

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
    volumes:
      - ./confs/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    networks:
      - my_net

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    hostname: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./run_kafka_workaround.sh:/tmp/run_kafka_workaround.sh
    ports:
      - "9092:9092"
      - "9101:9101"
    command: >
      bash -c "chmod +x /tmp/run_kafka_workaround.sh &&
               /tmp/run_kafka_workaround.sh && /etc/confluent/docker/run"
    networks:
      - my_net

networks:
  my_net:
