apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsrv-poc
  template:
    metadata:
      labels:
        app: obsrv-poc
    spec:
      containers:
        - name: obsrv-poc
          image: modicnvrg/observability-poc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
#            - name: CX_TOKEN
#              value: cxtp_oxXp9dX3lPQ4vY3qM4HlqH7eZowc37
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: traces-collector-addr
              value: $(NODE_IP):4317
