apiVersion: v1
kind: Service
metadata:
  name: obsrv-poc
spec:
  selector:
    app: obsrv-poc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # Use NodePort for Minikube
