apiVersion: v1
kind: Service
metadata:
  name: tracing-poc-service
spec:
  selector:
    app: tracing-poc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort  # Use NodePort for Minikube
